### ISSUE TITLE
Checkpoints for debias-race

### ISSUE THREAD

**Issue by yueanga** [sail-sg/finetune-fair-diffusion#2]
Thank you for release the code and checkpoint! I wonder how to replicate the result for debias-race only, I don't find any relative checkpoint saddly. :(

**Comment by XudongOliverShen** [comment]
Hi @yueanga, thanks for your interest and for pointing out I missed uploading the debits-race experiment! I forgot about it because I thought we didn't report it in the paper; but now I realise we did in Table 1. I will upload the checkpoint and code for the debias-race experiment by March 31, hopefully much sooner.

**Comment by XudongOliverShen** [comment]
Hi, I just uploaded exp-6-debias-race and the checkpoint. Do let me know if there is any issues.
